# Generated by Django 3.2.8 on 2021-11-05 01:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nonce',
            field=models.IntegerField(default=users.models.generate_random_nonce),
        ),
    ]
