# Generated by Django 3.2.8 on 2021-11-05 18:14

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_address',
            field=base.models.AddressField(blank=True, max_length=256, null=True),
        ),
    ]
