# Generated by Django 3.2.8 on 2021-10-17 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layer',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.project'),
        ),
        migrations.AddField(
            model_name='asset',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.layer'),
        ),
    ]
