# Generated by Django 3.2.8 on 2021-10-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='discord',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='etherscan',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='opeansea',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='twitter',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.CharField(default='', max_length=256),
        ),
    ]
