# Generated by Django 3.2.8 on 2021-10-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20211026_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='opeansea',
            new_name='opensea',
        ),
    ]
