# Generated by Django 3.2.8 on 2021-10-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_rename_opeansea_project_opensea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='discord',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='etherscan',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='opensea',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='twitter',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
