# Generated by Django 3.2.8 on 2022-01-05 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_alter_contract_chain'),
        ('editor', '0009_auto_20211029_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='community.contract'),
        ),
    ]
