# Generated by Django 3.2.8 on 2021-11-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='symbol',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
