# Generated by Django 3.2.8 on 2021-11-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20211101_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='block_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('ERC20', 'ERC20'), ('ERC721', 'ERC721'), ('ERC1155', 'ERC1155')], max_length=64),
        ),
    ]
