# Generated by Django 3.2.8 on 2021-11-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_contract_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
