# Generated by Django 3.2.8 on 2021-11-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_contract_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='balance',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
