# Generated by Django 3.2.8 on 2021-11-05 18:14

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_contract_block_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='address',
            field=base.models.AddressField(max_length=256, unique=True),
        ),
    ]
