# Generated by Django 3.2.8 on 2021-11-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='body',
        ),
        migrations.AddField(
            model_name='reply',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
