# Generated by Django 3.2.8 on 2021-11-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_pixel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='chain',
            field=models.CharField(choices=[('ethereum', 'ethereum'), ('polygon', 'polygon')], default='ethereum', max_length=64),
        ),
    ]
