# Generated by Django 3.2.8 on 2022-01-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_alter_contract_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='chain',
            field=models.CharField(choices=[('eth', 'eth'), ('polygon', 'polygon'), ('rinkeby', 'rinkeby')], default='eth', max_length=64),
        ),
    ]
